[build-system]
requires = ["setuptools>=61.0,<74.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "Pyomo"
version = "6.8.2.dev0"
description = "Pyomo: Python Optimization Modeling Objects"
readme = {file = "README.md", content-type = "text/markdown"}
license = {text = "BSD"}
authors = [
    {name = "Pyomo Developer Team", email = "pyomo-developers@googlegroups.com"}
]
maintainers = [
    {name = "Pyomo Developer Team", email = "pyomo-developers@googlegroups.com"}
]
keywords = ["optimization"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: End Users/Desktop",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: BSD License",
    "Natural Language :: English",
    "Operating System :: MacOS",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: Unix",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
requires-python = ">=3.8"
dependencies = [
    "ply",
]

[project.urls]
Homepage = "http://pyomo.org"
Documentation = "https://pyomo.readthedocs.io/"
Source = "https://github.com/Pyomo/pyomo"

[project.optional-dependencies]
tests = [
    "coverage",
    "parameterized", 
    "pybind11",
    "pytest",
    "pytest-parallel",
]
docs = [
    "Sphinx>4",
    "sphinx-copybutton",
    "sphinx_rtd_theme>0.5",
    "sphinxcontrib-jsmath",
    "sphinxcontrib-napoleon",
    "sphinx-toolbox>=2.16.0",
    "sphinx-jinja2-compat>=0.1.1",
    "numpy",
    "scipy",
]
dev = [
    # Include test dependencies for development
    "coverage",
    "parameterized", 
    "pybind11",
    "pytest",
    "pytest-parallel",
]

[project.scripts]
pyomo = "pyomo.scripting.pyomo_main:main_console_script"

[project.entry-points."pyomo.command"]
"pyomo.help" = "pyomo.scripting.driver_help"
"pyomo.viewer" = "pyomo.contrib.viewer.pyomo_viewer"

[tool.setuptools]
packages = {find = {exclude = ["scripts"]}}

[tool.setuptools.package-data]
"pyomo.contrib.ampl_function_demo" = ["src/*"]
"pyomo.contrib.appsi.cmodel" = ["src/*"]
"pyomo.contrib.mcpp" = ["*.cpp"]
"pyomo.contrib.pynumero" = ["src/*", "src/tests/*"]
"pyomo.contrib.viewer" = ["*.ui"]
"pyomo.contrib.simplification.ginac" = ["src/*.cpp", "src/*.hpp"]